name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy clang-format clang cmake ninja-build g++ gcc

    - name: Run Clang-Format Check
      run: |
        find src/ include/ tests/ -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_CXX_STANDARD=23 \
          -G Ninja

    - name: Run Clang-Tidy
      run: |
        cd build
        clang-tidy -p . $(find ../src -name '*.cpp')

    - name: Build project
      run: |
        cmake --build build

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

